version: "3"
# The parser will ignore extension fields prefixed with x-
include:
  - path: ./proxy.yaml
x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped

services:
  #------------------------------------
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    depends_on:
      - mysql

  #-----------------------------------
  mysql:
    #image: mariadb:10.6.4-focal
    image: mysql:8
    #command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports: ["3306:3306"]
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
#--------------------------
volumes:
  db_data: {}
  wp_data: {}
